[servers]
server1 ansible_host=3.221.170.235
server2 ansible_host=44.215.127.196

[servers:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=./mpxupd.pem
ansible_python_interpreter=/usr/bin/python3